package common;

public enum Command {
    LOGIN,
    SIGN_UP,
    NICKNAME_UNAVAILABLE,
    REGISTER_ATTEMPT,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    TEXT_MESSAGE,
    SEND_FILE,
    RECEIVE_FILE,
    CLOSING_CONNECTION,
    FORBIDDEN_SYMBOL,
    TOO_MANY_CHARACTERS,
    PUSH_FRIENDS,
}
